Add handling for rich-messages and events.
gambry/dialogflow-webhook pull request #1
Opened 2023-02-02 14:18 UTC by d0t15t

2023-02-06 15:35 UTC, gambry commented
Apparently travis-ci.org is not usable for builds anymore, so please allow me few days to migrate to travis-ci.com (or anything similar).

This also requires tests.

2023-02-06 15:43 UTC, gambry requested changes

2023-02-06 15:43 UTC, gambry commented on src/Model/Webhook/Response.php
> +          $json['fulfillmentMessages'] = [
This shouldn't be hardcoded. We should have a Message class implementing `JsonSerializable()` so the logic in this block is delegated to Messages. Same for Event.

2023-02-07 08:28 UTC, gambry commented
@d0t15t I've got Travis CI working again.

2023-02-13 11:49 UTC, d0t15t commented
@gambry Thanks, I've added the classes.

2023-02-17 17:03 UTC, gambry commented
@d0t15t I'm closing this PR in favour of #3 .

Let's continue the conversation in there.
Thanks!

2023-02-17 17:03 UTC, closed without merging